spring.application.name=backend

#?????
server.port=8080

#?????
spring.datasource.url=jdbc:mysql://server.wangjunsheng.top:3306/sailtrack?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
spring.datasource.username=sailtrack
spring.datasource.password=sailtrackadmin12@

#????
spring.mail.host=smtp.163.com
spring.mail.port=465
spring.mail.username=tracksail@163.com
spring.mail.password=PEft9wgCWiXa8zzm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
